### ISSUE TITLE
API Services not working with certain types

### ISSUE THREAD

**Issue by oBusk** [ThreatConnect-Inc/angular2-threatconnect#3]
The `tc_resource_type.ts` miss some itemtypes and thus the service will fail when attempting to get anything with that type.

From what i can see the missing types are:

* ASN
* CIDR
* Mutex
* RegistryKey

* Campaign

**Comment by fhightower** [comment]
Thanks @oBusk . It looks like we are also missing the `User Agent` indicator type.

Ping @bcsummers : Do we have a timeline for getting these added to this project?

**Comment by bcsummers** [comment]
Our plans are to add these as they are required.  Since someone is asking for them I guess it's that time.  I start to take a look at these today and hopefully have it added by early next week.
